apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elearning
resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml